name: ERP-Development

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Upload files to server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_development_server }}
          username: ${{ secrets.ftp_development_username }}
          password: ${{ secrets.ftp_development_password }}
